version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
    ports:
      - 8081:8080
      - 50052:50051
    volumes:
      - ./data/Volumes:/var/lib/weaviate
    restart: always
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      OPENAI_APIKEY: $OPENAI_APIKEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-transformers,text2vec-openai,ref2vec-centroid,generative-openai'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - weaviate-network

  t2v-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
    restart: always
    networks:
      - weaviate-network

  streamlit:
    image: new_streamlit_app
    ports:
      - 8501:8501
    volumes:
      - .:/app
    environment:
      WEAVIATE_URL: http://weaviate:8080
      OPENAI_APIKEY: $OPENAI_APIKEY
    restart: always
    networks:
      - weaviate-network

networks:
  weaviate-network:
    external: true

volumes:
  weaviate_data: